#!/bin/sh /etc/rc.common

START=91
USE_PROCD=1

start_service()
{
	/usr/sbin/qmodem-settings apply-all >/dev/null 2>&1 &
}

reload_service()
{
	start_service
}

service_triggers()
{
	procd_add_reload_trigger qmodem
}
