#!/bin/sh
# Copyright (C) 2024 Tom <fjrcn@outlook.com>
manual=$(uci get -q modem.global.manual_configuration)
[ "${manual}" -eq 1 ] && exit
logger -t modem_hotplug "usb_event slot: ${DEVPATH} action: ${ACTION}"
[ -z "${DEVNUM}" ] && exit


slot=$(basename "${DEVPATH}")
logger -t modem_hotplug "usb_event run slot: ${slot} action: ${ACTION}"
case "${ACTION}" in
    bind|\
    add)
        /usr/share/modem/modem_scan.sh add "${slot}" usb
        ;;
    remove)
        /usr/share/modem/modem_scan.sh disable "${slot}" usb
        ;;
esac
