#!/bin/sh /etc/rc.common
USE_PROCD=1
START=30

set_rule()
{
    proto=$1
    policy=$2
    case $policy in
        0) 
            cmd="stop"
            ;;
        1)
            cmd="wan"
            ;;
        2)
            cmd="wwan"
            ;;
        3)
            cmd="lb"
            ;;
        *)
            cmd="stop"
            ;;
    esac
    logger -t modem_mwan "before set $proto $cmd"
    /usr/share/modem/modem_mwan.sh $proto $cmd
    logger -t modem_mwan "set $proto $cmd"

}




start_service() {
    logger -t modem_mwan "start modem_mwan"
	config_load modem_mwan
    config_get enable global enable_mwan 0
    if [ "$enable" = "0" ]; then
        stop_service
    fi
    config_get v4 ipv4 mwan_policy 0
    set_rule ipv4 $v4
}

stop_service() {
    /usr/share/modem/modem_mwan.sh ipv4 stop
    /usr/share/modem/modem_mwan.sh ipv4 disable
}

service_triggers() {
	procd_add_reload_trigger 'modem_mwan'
}
