#!/bin/sh

. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

modem_settings()
{
	local board="$1"

	case $board in
	HC,HC-G80)
		add_ipv4_config "1_1_1" 2 1
		add_ipv4_config "1_1_4" 2 1
		add_ipv4_config "2_1" 1 1
		uci commit qmodem_mwan
		;;
	huasifei,ws3006)
		add_ipv4_config "5g0"  1 230
		add_ipv4_config "5g1" 1 230
		add_ipv4_config "4g0" 20 1
		add_ipv4_config "4g1" 20 1
		add_ipv4_config "4g2" 20 1
		add_ipv4_config "4g3" 20 1
		uci commit qmodem_mwan
		;;
	
	esac
}


add_ipv4_config(){
	local interface_name="$1"
	cfg=$(uci add qmodem_mwan ipv4)
uci batch<<-EOF >/dev/null
set qmodem_mwan.$cfg.member_interface=$interface_name
set qmodem_mwan.$cfg.member_priority=$2
set qmodem_mwan.$cfg.member_weight=$3
add_list qmodem_mwan.$cfg.member_track_ip='test.ustc.edu.cn'
add_list qmodem_mwan.$cfg.member_track_ip='cip.cc'
add_list qmodem_mwan.$cfg.member_track_ip='208.67.220.220'
add_list qmodem_mwan.$cfg.member_track_ip='208.67.222.222'
EOF
}




board=$(board_name)
modem_settings $board
exit 0
