#!/bin/sh

. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

modem_settings()
{
	local board="$1"

	case $board in
	arcadyan,aw1000)
		#usb slot
		uci set qmodem.usb0="modem-slot"
		uci set qmodem.usb0.slot="4-1"
		uci set qmodem.usb0.type="usb"
		uci set qmodem.usb0.net_led="ipq::led9"
		uci set qmodem.usb0.sim_led="ipq::led2"
		uci set qmodem.usb0.alias="wwan0"
		#pcie slot
		uci set qmodem.pcie0="modem-slot"
		uci set qmodem.pcie0.slot="0000:01:00.0"
		uci set qmodem.pcie0.type="pcie"
		uci set qmodem.pcie0.net_led="ipq::led9"
		uci set qmodem.pcie0.sim_led="ipq::led2"
		uci set	qmodem.pcie0.associated_usb='4-1'
		uci set qmodem.pcie0.alias="wwan1"
		uci commit qmodem
		;;
	HC,HC-G80)
		#mini pci slot
		uci set qmodem.mini_pci="modem-slot"
		uci set qmodem.mini_pci.slot="1-1.4"
		uci set qmodem.mini_pci.type="usb"
		uci set qmodem.mini_pci.net_led="wwan"
		#m.2 slot (usb2.0)
		uci set qmodem.m2_u2="modem-slot"
		uci set qmodem.m2_u2.slot="1-1.1"
		uci set qmodem.m2_u2.type="usb"
		uci set qmodem.m2_u2.net_led="wwan"
		uci set qmodem.m2_u2.ethernet_5g="cpewan0"
		#m.2 slot (usb3.0)
		uci set qmodem.m2_u3="modem-slot"
		uci set qmodem.m2_u3.slot="2-1"
		uci set qmodem.m2_u3.type="usb"
		uci set qmodem.m2_u3.net_led="wwan"
		uci set qmodem.m2_u3.ethernet_5g="cpewan0"
		uci commit qmodem
		;;
	huasifei,ws3006)
	#m2 usb3.0 
	#(slot 2)
		uci set qmodem.5g1="modem-slot"
		uci set qmodem.5g1.slot="2-1.2"
		uci set qmodem.5g1.alias="5g1"
		uci set qmodem.5g1.type="usb"
		uci set qmodem.5g1.net_led="green:5g2"
		uci set qmodem.5g1.sim_led="green:sim2"
	#(slot 1)
		uci set qmodem.5g0="modem-slot"
		uci set qmodem.5g0.slot="2-1.4"
		uci set qmodem.5g0.alias="5g0"
		uci set qmodem.5g0.type="usb"
		uci set qmodem.5g0.net_led="green:5g1"
		uci set qmodem.5g0.sim_led="green:sim1"
	#m2 usb2.0 
	#(slot 2)
		uci set qmodem.4g3="modem-slot"
		uci set qmodem.4g3.slot="1-1.1"
		uci set qmodem.4g3.type="usb"
		uci set qmodem.4g3.alias="4g3"
		uci set qmodem.4g3.net_led="green:5g2"
		uci set qmodem.4g3.sim_led="green:sim2"
	#(slot 1)
		uci set qmodem.4g2="modem-slot"
		uci set qmodem.4g2.slot="1-1.4"
		uci set qmodem.4g2.alias="4g2"
		uci set qmodem.4g2.type="usb"
		uci set qmodem.4g2.net_led="green:5g1"
		uci set qmodem.4g2.sim_led="green:sim1"
	#mini pci slot
	#(slot 2)
		uci set qmodem.4g1="modem-slot"
		uci set qmodem.4g1.slot="1-1.2"
		uci set qmodem.4g1.type="usb"
		uci set qmodem.4g1.alias="4g1"
		uci set qmodem.4g1.net_led="green:5g2"
		uci set qmodem.4g1.sim_led="green:sim2"
	#(slot 1)
		uci set qmodem.4g0="modem-slot"
		uci set qmodem.4g0.slot="1-1.3"
		uci set qmodem.4g0.type="usb"
		uci set qmodem.4g0.alias="4g0"
		uci set qmodem.4g0.net_led="green:5g1"
		uci set qmodem.4g0.sim_led="green:sim1"

		uci commit qmodem
		;;
	cyber,cyber3588-aib)
uci batch << EOF
set	qmodem.m2_0=modem-slot
set	qmodem.m2_0.type='pcie'
set	qmodem.m2_0.slot='0001:11:00.0'
set	qmodem.m2_0.net_led='blue:status'
set	qmodem.m2_0.associated_usb='8-1'
set	qmodem.m2_0.sim_led='green:status'
commit qmodem
EOF
	esac
}

board=$(board_name)
modem_settings $board
exit 0
