#!/bin/sh
# Copyright (C) 2024 Tom <fjrcn@outlook.com>

/etc/init.d/modeminit enable
/etc/init.d/modem enable

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@qmodem[-1]
	delete ucitrack.@qmodem[-1]
	add ucitrack qmodem
	set ucitrack.@qmodem[-1].init=qmodem_network
	add ucitrack qmodem
	set ucitrack.@qmodem[-1].init=qmodem_mwan
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
